name: Run Ansible playbook
description: Execute Ansible playbook on selected hosts
branding:
  color: red
  icon: play
inputs:
  playbook:
    description: Ansible playbook filepath
    required: true
  key:
    description: SSH private key used to connect to the host
    required: false
  inventory:
    description: Custom content to write into hosts
    required: false
  config:
    description: Ansible config file
    required: false
  vault_config:
    description: Vault config file
    required: false
  vault_password:
    description: The password used for decrypting vaulted files
    required: false
  known_hosts:
    description: Contents of SSH known_hosts file
    required: false
  files:
    description: Files to copy to host
    required: false
  options:
    description: Extra options that should be passed to ansible-playbook command
    required: false
outputs:
  output:
    description: The captured output of both stdout and stderr from the Ansible Playbook run
runs:
  using: node12
  main: main.js
  post: post.js
