name: Test Ansible Action

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
jobs:
  remote:
    runs-on: ubuntu-latest
    env:
      SSH_PUBLIC_KEY: |
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDDWY9FVubMDUsZZuT2uT2U3ELfgztmUIeL84CCCUy0V8/p/3mGg0CZKCCiaVOBA3KyTX+RN+FW4i9UNWuhNXqLLEzpvR4E7BIyCVmfrQ89kJfMX5Wy1+sxQflV09u5qFVNbjneDVkCHAD4Q8MEwSnZXPNtmBft0I7RadisiteSd+In6w1gStWb1apjnxrtqiJjh4KBEP/0UYzIahByua4c9Hq0oI3TMihUqX/CPNYfaNFSFFtlt/tXvZU36VbAnJyIftX5KXhhmKhv8mZbQUg9xZySg7X6EtQBDQulJqgLLPu5r4bTCBGh4sfdzfbJBWMAcV6xjNDKaGf8pVkFE990jYePOqP5ydi/J/LS3dHz8rqt261FJhpCip8VoXGha2Xn0H+/n8gQTuzRmzLYHlknhJt1izWUDvhRQaf5eNdWivtNPG8NYFXzeekcUYE6GfeCpItFxnwktvspjkIaFunLfPvLkkNjSViJlpZdNRCYg59fnhyxO7jT7IKeUKNEdoM=
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup remote
        run: |
          echo "$SSH_PUBLIC_KEY" | sudo tee /etc/ssh/authorized_keys
          sudo tee /etc/ssh/sshd_config <<EOF
            PasswordAuthentication no
            PubkeyAuthentication yes
            AuthorizedKeysFile /etc/ssh/authorized_keys
            PermitRootLogin no
            Subsystem sftp /usr/lib/openssh/sftp-server
          EOF
          sudo systemctl restart sshd
          echo 'SSH_KNOWN_HOSTS<<EOF' >> $GITHUB_ENV
          echo $(ssh-keyscan localhost) >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: TDV Provision
        uses: ./.github/actions/ansible-playbook
        with:
          playbook: tdv/tdv.yml
          inventory: tdv/tdv.ini
          key: tdv/tdv_key.pem
          vault_config: tdv/tdv_vault
          vault_password: uUdPrUtn64aJfMSK
          known_hosts: ${{env.SSH_KNOWN_HOSTS}}
          files: |
            files/tls.crt
            files/tls.priv.pem
          options: |
            --verbose

      - name: Test files
        run: |
          pwd
          ls -al files
          ls -al tdv/files
